### ISSUE TITLE
[QUESTION] Cross-region logs in a single Sink

### ISSUE THREAD

**Issue by oieduardorabelo** [aws-samples/cloudwatch-obervability-access-manager-terraform#3]
hello everyone, and thanks for sharing this solution.

while reading this repository readme and the doc page [CloudWatch Unified Cross Account](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html)

one question is still not answered clearly:

**Q: cross-account cross-region logs to a single-account single-region is still not possible out of the box?**

my understanding of OAM Sink and Link is that they are bound to a single region, correct?

isn't possible to create a Sink (us-east-1) and Link multiple regions (ap-southeast-2, eu-west-2) to the same Sink (us-east-1)?

![image](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/2e766f63-600f-4c7d-bfde-d5c77ad21ae0)

**Comment by pmvrak** [comment]
Yes that's right. The Sink and Link have to be in same region. I'm adding this as part of **Limitations** section.

**Comment by pmvrak** [comment]
Users can still do cross-account and cross-region Observability. Please see this documentation for  cross-account and cross-region monitoring.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Cross-Account-Cross-Region.html

**Comment by oieduardorabelo** [comment]
thank you so much for answering @pmvrak 💪

the link you provided states in the beginning:

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Cross-Account-Cross-Region.html

> CloudWatch also offers a cross-account, cross-Region CloudWatch dashboard. This functionality provides you with cross-account visibility to your dashboards, alarms, metrics, and automatic dashboards. It does not provide cross-account visibility for logs or for traces.

Logs are not included in this cross-account cross-region solution from CloudWatch.

- Sink+Link are bounded by region and you can have only a single Sink per account
- Logs aren't included in the **Cross-account cross-Region CloudWatch console** (from the link above).

This results in me still being required to export logs with CloudWatch Destination + Kinesis Stream and centralize them in a single-region in a Monitoring Account. This diagram illustrates what I'm doing at the moment:

![image](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/746ceb1c-eafe-463f-a862-aaf04fe07df8)

From the Monitoring account above, I can access the alarms, metrics, and automatic dashboards via cross-account sharing (the link you shared), but the logs I need to manually forward them to the monitoring account single-region.

**Comment by pmvrak** [comment]
Hi Eduardo, yes thats the right approach. Nice architecture diagram and flow. Also on a side note an would also suggest to look at [OpenSearch Solution which can be better suited as well](https://docs.aws.amazon.com/solutions/latest/centralized-logging-on-aws/solution-overview.html) as well which uses OpenSearch for central processing of your logs. So its can be a combination of OAM plus the Centralized logging solution using OpenSearch together?

**Comment by sweldon** [comment]
Just wanted to confirm something, if anyone sees this:
> Sink+Link are bounded by region and you can have only a single Sink per account

This no longer seems to be the case in practice. It appears that you can now have a single sink aggregate data across many source accounts from multiple regions, which you can then link by doing, for example:
```
aws oam link --sink-arn arn:aws:oam:region:account-id:sink/sink-name --source-account-id 111122223333 --source-regions us-east-1,us-west-2
```
- Notice the sink name (which can be shared across regions in the monitoring account, regardless of sink ARN) and source- regions

Can anyone confirm if this is true at scale? [The documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-oam-sink.html) still seems to suggest you can only have 1 sink per region, but it clearly looks to be incorrect. Not sure if I'm misunderstanding something.

I also asked Amazon Q about this, and got the following:

It is possible to have a CloudWatch Observability Access Manager sink in multiple regions for a single account. When creating the sink, you can associate it with one or more regions in that account. The sink will then aggregate data from all of the linked regions.

Some key points:
 - A single sink can be linked to all supported regions in the target/monitoring account.
 - The same sink name must be configured in each source region that will send data to the sink.
 - All observability data, including metrics, logs and traces, will be centrally available in the monitoring account regardless of which regions it originated from.

 This allows monitoring an application that spans regions from a single consolidated view without having to worry about regional boundaries.

Try it out yourself, seems to be legit, but would love official confirmation.

**Comment by oieduardorabelo** [comment]
@sweldon could you confirm which API you are trying to use?

the AWS OAM CLI don't have a `aws oam link` command:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/oam/index.html

The `create-link` command (from the documentation link above), only accepts a single region:

```bash
  create-link
--label-template <value>
--resource-types <value>
--sink-identifier <value>
[--tags <value>]
[--cli-input-json | --cli-input-yaml]
[--generate-cli-skeleton <value>]
[--debug]
[--endpoint-url <value>]
[--no-verify-ssl]
[--no-paginate]
[--output <value>]
[--query <value>]
[--profile <value>]
[--region <value>]
[--version <value>]
[--color <value>]
[--no-sign-request]
[--ca-bundle <value>]
[--cli-read-timeout <value>]
[--cli-connect-timeout <value>]
[--cli-binary-format <value>]
[--no-cli-pager]
[--cli-auto-prompt]
[--no-cli-auto-prompt]
```

following the current v2 API definitions, the quote:

> Sink+Link are bounded by region and you can have only a single Sink per account

is still true and the current behaviour of OAM

---

that said, in Jan 2024, CloudWatch Logs released the "account level subscription filter":

https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-cloudwatch-logs-account-level-subscription-filter/

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters-AccountLevel.html

with that, you can have a single subscription in your account to send logs to the centralized account (no need for multiple sinks anymore)

i wrote a guide about it on:

**CloudWatch Strategies for Cross-Account and Cross-Region Log Aggregation**
https://blog.awsfundamentals.com/cloudwatch-logs-strategies-for-cross-account-and-cross-region-aggregation

**Comment by sweldon** [comment]
Hi @oieduardorabelo, thank you for the reply! Apologies I used the wrong CLI example there (Amazon Q led me astray), but regardless, I just confirmed that I was able to create 2 sinks in 1 account, 1 in us-east-1, and 1 in us-west-2. I was then able to create links to both of those sinks from a different account, in the respective regions. Am i misunderstanding this? Are these actually *one* sink, just bounded by region? They have different ARNs, so I wouldnt think that would be the case. For my use case, I am OK with switching between regions in the global monitoring account, but just want to confirm the "one sink per account" concept here.

**Monitoring Account**, 2 sinks in 2 regions
```
➜  ~ aws oam list-sinks --region us-east-1
{
    "Items": [
        {
            "Arn": "arn:aws:oam:us-east-1:<accountid>:sink/<sinkid>",
            "Id": "<sinkid>",
            "Name": "observabilitySink"
        }
    ]
}
```
```
➜  ~ aws oam list-sinks --region us-west-2
{
    "Items": [
        {
            "Arn": "arn:aws:oam:us-west-2:<accountid>:sink/<sinkid>",
            "Id": "<sinkid>",
            "Name": "observabilitySinkUsWest2"
        }
    ]
}
```
**Source Account**, linked to 2 regional sinks in the same monitoring account
```
➜  scripts aws oam list-links --region us-east-1
{
    "Items": [
        {
            "Arn": "arn:aws:oam:us-east-1:<sourceaccountid>:link/<linkid>",
            "Id": "<linkid>",
            "Label": "<label>",
            "ResourceTypes": [
                "AWS::ApplicationInsights::Application",
                "AWS::Logs::LogGroup",
                "AWS::CloudWatch::Metric",
                "AWS::XRay::Trace"
            ],
            "SinkArn": "arn:aws:oam:us-east-1:<monitoringaccountid>:sink/<sinkid-us-east-1>"
        }
    ]
}
```
```
➜  scripts aws oam list-links --region us-west-2
{
    "Items": [
        {
            "Arn": "arn:aws:oam:us-west-2:<sourceaccountid>:link/<linkid>"",
            "Id": "<linkid>"",
            "Label": "test-link-us-west-2",
            "ResourceTypes": [
                "AWS::Logs::LogGroup"
            ],
            "SinkArn": "arn:aws:oam:us-west-2:<monitoringaccountid>:sink/<sinkid-us-west-2>"
        }
    ]
}
```

I also confirmed this works by sending some logs to source account 1 in us-west-2, and they were reflected in the us-west-2 monitoring account. Did the same for us-east-1 on both. **So the documentation of "1 sink per account" has to be incorrect, right?**

Thank you again for the awesome resources provided, excellent and very informative blog post. Your custom approach does look to be a great option if I cannot use OAM. Much appreciated!

**Comment by oieduardorabelo** [comment]
@sweldon holy shit man, yes, it does work!! 🤯

i tested in multiple independent AWS accounts and with a new AWS Organization

the centralized monitoring account can have:

- 1 Sink per Region (not per account as described in the documentation)
- We can create a Sink in us-east-1, ap-southeast-2, eu-west-1 etc

this pattern is now possible with Sink+Link:

![image](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/fc64c7af-35fb-4b04-a69e-387a51b4e8c4)

not sure if that is a bug, but it does work 😄

i can even use log insights across accounts for the same region, in the monitoring account:

![CleanShot 2024-03-29 at 02 37 01](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/7925f10a-c76d-4f5d-8d0b-b7b2a12f2a60)

![CleanShot 2024-03-29 at 02 37 30](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/fdc8d39d-c514-47db-a55e-9b6e87544bd6)

![CleanShot 2024-03-29 at 02 38 12](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/fae7eedf-5bf6-462b-8a81-25a482c9e69c)

i still need to test the limits in the source account, as described in:

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html

> OAM source account links
> Each source account can be linked to as many as 5 monitoring accounts
> This quota can't be changed.

If this quota still applies in the account level, it means we can only connect 5 regions of the 33 regions aws have

but for the monitoring account, now we can aggregate cloudwatch metrics, logs, traces and application insights 🥳

with everything in the same account, we can create cross-region dashboards in the monitoring account to have an overview across regions

fantastic discovery!

**Comment by sweldon** [comment]
@oieduardorabelo 👏 👏 👏  Glad I could help and thanks for the confirmation! Quick follow-up:

> Each source account can be linked to as many as 5 monitoring accounts
> ...
> If this quota still applies in the account level, it means we can only connect 5 regions of the 33 regions aws have

Couldn't you still link all 33 regions to their respective regional sinks in 1 monitoring account? It doesn't appear that accounts are limited to linking to 5 sinks, but 5 accounts as a whole. So i feel like 1 monitoring account with sinks in every region is enough to service all regions for all of your source accounts, correct? 

Also just wanted to let you know that there is a small typo in the new diagram, top right orange "cross-account eu-west-1 aggregation" should be "ap-southeast-2" I think 😃 

I've submitted a request for AWS to update their [documentation here](https://docs.aws.amazon.com/OAM/latest/APIReference/API_CreateSink.html) for the sink limitations
