### ISSUE TITLE
Cross region monitoring

### ISSUE THREAD

**Issue by afreyermuth98** [aws-samples/cloudwatch-obervability-access-manager-terraform#4]
Hello there.
I want to monitor my infrastructure using Cloudwatch observability access manager.
I have 2 accounts : AccountA on us-east-1 and AccountB on us-east-2.
I've realized that if I want to connect these 2 accounts I need to make the sink on the same region. 
AccountA is my monitoring account and AccountB is my source account.
I would expect that all the metrics logs etc ... from AccountB where available on AccountA but this is not the case.
Is this "normal" ? Is there a way to get these metrics logs ... from us-east-2 inside AccountA ?
I've enabled the `View cross-account cross-region` inside AccountB but it didn't change anything.

Thanks by advance !

**Comment by pmvrak** [comment]
Below are Limitations and caveats for cross-region setup -

_Limitations_

Observability Access Manager has the following service quotas, which cannot be changed. Consider these quotas before you deploy this feature. For more information, see [CloudWatch service quotas](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html) in the CloudWatch documentation.

Source account links: You can link each source account to a maximum of five monitoring accounts.

Sinks: You can use only one sink per account.

_In addition:_

Sinks and links must be created in the same AWS Region; they cannot be cross-Region.

For cross-Region, cross-account monitoring, you can create [cross-account and cross-region CloudWatch dashboards](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Cross-Account-Cross-Region.html) for alarms and metrics, except for logs and traces. Another option is to [create centralized logging by using Amazon OpenSearch Service.](https://aws.amazon.com/solutions/implementations/centralized-logging-with-opensearch/)
