### ISSUE TITLE
OAM Sink now supports multiple regions 

### ISSUE THREAD

**Issue by oieduardorabelo** [aws-samples/cloudwatch-obervability-access-manager-terraform#5]
hey @pmvrak

following the discussion from my previous question https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/issues/3

i'm happy to say that we can create multiple Sink in the monitoring account 🚀

The limitation of 1 Sink per account is no more

i believe the quota documentation will need to be updated: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html

the following pattern is now possible with OAM Sink+Link:

![image](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/942917cb-6cfb-422f-bbcb-9b89ab7f84c8)

- Monitoring account can have 1 Sink per region (us-east-1, ap-southeast-2, eu-west-2 etc)
- Source account can have 1 Link per region (us-east-1, ap-southeast-2, eu-west-2 etc)
- Source account connects Link-region to Sink-region

Monitoring account receives metrics, logs, traces, and application insights from all accounts in the same destination region

The aggregation is per region, we can't send longs from RegionA to RegioB, for example:

AccountA-us-east-1, AccountB-us-east-1, AccountC-us-east-1 => Monitoring-us-east-1

AccountA-ap-southeast-2, AccountB-ap-southeast-2, AccountC-ap-southeast-2 => Monitoring-ap-southeast-2

In the following screenshots, my monitoring account have 2 Sinks, one for ap-southeast-2 and us-east-1

I'm receiving logs from 2 different accounts and I can use Log Insights to query cross-account logs for the same region

![image](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/4113b138-9220-4311-9354-b8eb45f22aaf)

![image](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/0cbf975a-c474-48e3-bf35-ef5b3e0fb20e)

![image](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/a3c48264-17fc-469e-9e74-c62b7c168f67)

Big shout out to @sweldon for joining the discussion, questions, and discovery! 

This is a significant step forward in CloudWatch governance and enterprise features.

**Comment by oieduardorabelo** [comment]
i sent a feedback in the documentation page asking for clarification on the wording

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html

because Sink and Link are bounded by Region, using the word "account" is creating confusion and misleading solutions

![CleanShot 2024-03-29 at 16 50 58](https://github.com/aws-samples/cloudwatch-obervability-access-manager-terraform/assets/829902/2bd55d77-112d-4f7d-ad66-8f624bf99feb)

**Comment by pmvrak** [comment]
Hi @oieduardorabelo @sweldon thanks for checking it out and coming back with new feature tests. Let me test it as well with code and come back with results but definitely sinks in every region is great feature addition :)

**Comment by pmvrak** [comment]
I have updated the article to include new feature of sink per region. The new version will be published soon. Thanks @oieduardorabelo @sweldon
